@MVBooksAppService_HostAddress = http://localhost:5106

GET {{MVBooksAppService_HostAddress}}/books/
Accept: application/json
###

GET {{MVBooksAppService_HostAddress}}/books/5
Accept: application/json
###
